(defun compile-hhub-files ()
  (let ((filelist (list 
"dod-bl-bo.lisp" 
"dod-bl-cmp.lisp"
"dod-bl-cus.lisp" 
"dod-bl-odt.lisp" 
"dod-bl-opf.lisp"
"dod-bl-ord.lisp"
"dod-bl-pay.lisp"
"dod-bl-pol.lisp"
"dod-bl-prd.lisp"
"dod-bl-usr.lisp"
"dod-bl-utl.lisp"
"dod-bl-ven.lisp"
"dod-bo.lisp"
"dod-dal-act.lisp"
"dod-dal-bo.lisp"
"dod-dal-cmp.lisp"
"dod-dal-cus.lisp"
"dod-dal-odt.lisp"
"dod-dal-opf.lisp"
"dod-dal-ord.lisp"
"dod-dal-otk.lisp"
"dod-dal-oty.lisp"
"dod-dal-pay.lisp"
"dod-dal-pol.lisp"
"dod-dal-prd.lisp"
"dod-dal-rol.lisp"
"dod-dal-usr.lisp"
"dod-dal-ven.lisp"
"dod-dal-vnd.lisp"
"dod-ini-sys.lisp"
"dod-ui-act.lisp"
"dod-ui-attr.lisp"
"dod-ui-cad.lisp"
"dod-ui-cmp.lisp"
"dod-ui-cus.lisp"
"dod-ui-odt.lisp"
"dod-ui-opf.lisp"
"dod-ui-ord.lisp"
"dod-ui-oty.lisp"
"dod-ui-pay.lisp"
"dod-ui-pol.lisp"
"dod-ui-prd.lisp"
"dod-ui-rol.lisp"
"dod-ui-sys.lisp"
"dod-ui-usr.lisp"
"dod-ui-utl.lisp"
"dod-ui-ven.lisp"))
(path "~/dairyondemand/hhub/"))

(mapcar (lambda (file)
	  (compile-file (concatenate 'string path file))) filelist)))
