SELECT 'Dropping database CRMCOREDB' AS ' ';
DROP DATABASE IF EXISTS CRMCOREDB;


DROP USER  'TestCRMCore'@'localhost';
CREATE USER 'TestCRMCore'@'localhost' IDENTIFIED BY 'TestCRMCore';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE   ON CRMCOREDB.*   TO 'TestCRMCore'@'localhost';

SELECT 'Creating database CRMCOREDB' AS ' ';
CREATE DATABASE CRMCOREDB;

USE CRMCOREDB;

SELECT 'dropping the tables' AS ' ';
 DROP TABLE IF EXISTS CRM_ACCOUNT;
 DROP TABLE IF EXISTS CRM_COMPANY;
 DROP TABLE IF EXISTS CRM_OPPORTUNITY;
 DROP TABLE IF EXISTS CRM_USERS;
 DROP TABLE IF EXISTS CRM_ACCT_USERS;
 DROP TABLE IF EXISTS CRM_OPTY_USERS;
 DROP TABLE IF EXISTS CRM_ACCT_OPTY;
 DROP TABLE IF EXISTS CRM_ROLES;
 DROP TABLE IF EXISTS CRM_USER_ROLES;
 DROP TABLE IF EXISTS CRM_PRIVILEGES;
 DROP TABLE IF EXISTS CRM_ROLE_PRIVILEGES;
 DROP TABLE IF EXISTS CRM_ACCOUNT_TYPES;
 
 SELECT 'tables dropped' AS ' ';

SELECT 'creating table CRM_COMPANY' AS ' ';
CREATE TABLE CRM_COMPANY( ROW_ID MEDIUMINT AUTO_INCREMENT     PRIMARY KEY ,
 NAME VARCHAR(255) ,
 ADDRESS VARCHAR(512) ,
 PRIMARY_CONTACT VARCHAR(255), 
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
  CREATED_BY MEDIUMINT,
  UPDATED TIMESTAMP ,
  UPDATED_BY MEDIUMINT,
  ACTIVE_FLG CHAR(1),
 DELETED_STATE CHAR(1));
 
SELECT 'creating table CRM_USERS' AS ' ';    
CREATE TABLE CRM_USERS( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
 NAME VARCHAR(30) ,
 USERNAME VARCHAR(30) ,
 PASSWORD VARCHAR(100) ,
 EMAIL VARCHAR(255),
 FIRSTNAME VARCHAR(50), 
 LASTNAME VARCHAR(50), 
 FULLNAME VARCHAR(50), 
 SALUTATION VARCHAR(10), 
 TITLE VARCHAR(255), 
 PHONE_HOME VARCHAR(50), 
 PHONE_MOBILE VARCHAR(50), 
 PHONE_OFFICE VARCHAR(50), 
 PRIMARY_ADDRESS_STREET VARCHAR(150), 
 PRIMARY_ADDRESS_CITY VARCHAR(100), 
 PRIMARY_ADDRESS_STATE VARCHAR(100), 
 PRIMARY_ADDRESS_POSTALCODE VARCHAR(20), 
 PRIMARY_ADDRESS_COUNTRY VARCHAR(255), 
 BIRTHDATE DATETIME, 
 PICTURE VARCHAR(255),
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 CREATED_BY MEDIUMINT,
 UPDATED TIMESTAMP ,
 UPDATED_BY MEDIUMINT,
 ACTIVE_FLG CHAR(1),
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT, 
PARENT_ID MEDIUMINT );
 
 
SELECT 'creating table CRM_ACCOUNT' AS ' ';    
CREATE TABLE CRM_ACCOUNT( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
ACCOUNT_NO VARCHAR(10),
 NAME VARCHAR(30) ,
 DESCRIPTION VARCHAR(255),
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 CREATED_BY MEDIUMINT,
 UPDATED TIMESTAMP ,
 UPDATED_BY MEDIUMINT,
 ACTIVE_FLG CHAR(1),
 DEFAULT_FLG CHAR(1),
 ACCOUNT_TYPE  MEDIUMINT,
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT, 
PARENT_ID MEDIUMINT );

CREATE TABLE CRM_ACCOUNT_TYPE (ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY, 
NAME VARCHAR(50), 
DESCRIPTION VARCHAR(255));




SELECT 'creating table CRM_OPPORTUNITY' AS ' ';
CREATE TABLE CRM_OPPORTUNITY (ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
OPPORTUNITY_ID VARCHAR(10),
NAME VARCHAR(60),
DESCRIPTION VARCHAR(255),
CREATED TIMESTAMP NOT NULL DEFAULT NOW(),
 CREATED_BY MEDIUMINT,
 UPDATED TIMESTAMP ,
 UPDATED_BY MEDIUMINT,
 ACTIVE_FLG CHAR(1),
 DEFAULT_FLG CHAR(1),
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT, 
PARENT_ID MEDIUMINT); 


SELECT 'creating table CRM_OPTY_USERS' AS ' ';
CREATE TABLE CRM_OPTY_USERS( ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY, 
OPTY_ID MEDIUMINT, 
USER_ID MEDIUMINT, 
TENANT_ID MEDIUMINT); 

SELECT 'creating table CRM_ACCT_USERS' AS ' ';
CREATE TABLE CRM_ACCT_USERS(ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
USER_ID MEDIUMINT, 
ACCT_ID MEDIUMINT, 
TENANT_ID MEDIUMINT);

SELECT 'creating table CRM_ACCT_OPTY' AS ' ';
CREATE TABLE CRM_ACCT_OPTY( ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY, 
OPTY_ID MEDIUMINT, 
ACCT_ID MEDIUMINT, 
AMOUNT DECIMAL(5,2), 
DESCRIPTION VARCHAR(100),
CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 CREATED_BY MEDIUMINT,
 UPDATED TIMESTAMP ,
 UPDATED_BY MEDIUMINT,
TENANT_ID MEDIUMINT);



SELECT 'creating table CRM_ROLES' AS ' ';
CREATE TABLE CRM_ROLES(ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY, 
NAME VARCHAR(30), 
DESCRIPTION VARCHAR(255), 
CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 CREATED_BY MEDIUMINT,
 UPDATED TIMESTAMP ,
 UPDATED_BY MEDIUMINT,
 ACTIVE_FLG CHAR(1),
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT, 
PARENT_ID MEDIUMINT );

SELECT 'Creating table CRM_ROLE_PRIVILEGES' AS ' ';
CREATE TABLE CRM_PRIVILEGES ( ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(30),
DESCRIPTION VARCHAR(255),
CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 CREATED_BY MEDIUMINT,
 UPDATED TIMESTAMP ,
 UPDATED_BY MEDIUMINT,
 ACTIVE_FLG CHAR(1),
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT, 
PARENT_ID MEDIUMINT );

SELECT 'Creating table CRM_USER_ROLES' AS ' ';
CREATE TABLE CRM_USER_ROLES( ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
USER_ID  MEDIUMINT,
ROLE_ID MEDIUMINT,
TENANT_ID MEDIUMINT);

SELECT 'Creating table CRM_ROLE_PRIVILEGES' AS ' ';
CREATE TABLE CRM_ROLE_PRIVILEGES ( ROW_ID MEDIUMINT AUTO_INCREMENT PRIMARY KEY,
ROLE_ID MEDIUMINT,
PRIVILEGE_ID MEDIUMINT,
TENANT_ID MEDIUMINT); 




-- Create foreign key references : CRM_USERS Table
SELECT 'Create foreign key references : CRM_USERS Table' AS ' '; 
ALTER TABLE CRM_USERS ADD FOREIGN KEY( TENANT_ID)   REFERENCES CRM_COMPANY(ROW_ID); 


-- Create foreign key references : CRM_ACCOUNT Table
SELECT 'Create foreign key references : CRM_ACCOUNT Table' AS ' ';
ALTER TABLE CRM_ACCOUNT ADD FOREIGN KEY (CREATED_BY) REFERENCES CRM_USERS(ROW_ID); 
ALTER TABLE CRM_ACCOUNT ADD FOREIGN KEY (UPDATED_BY) REFERENCES CRM_USERS(ROW_ID);     
ALTER TABLE CRM_ACCOUNT ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID); 
ALTER TABLE CRM_ACCOUNT ADD FOREIGN KEY (ACCOUNT_TYPE) REFERENCES CRM_ACCOUNT_TYPE(ROW_ID);


-- Create foreign key references : CRM_OPPORTUNITY Table
SELECT 'Create foreign key references : CRM_OPPORTUNITY Table' AS ' ';
ALTER TABLE CRM_OPPORTUNITY ADD FOREIGN KEY (CREATED_BY) REFERENCES CRM_USERS(ROW_ID); 
ALTER TABLE CRM_OPPORTUNITY ADD FOREIGN KEY (UPDATED_BY) REFERENCES CRM_USERS(ROW_ID);     
ALTER TABLE CRM_OPPORTUNITY ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID); 

-- Create foreign key references : CRM_OPTY_USERS
SELECT 'Create foreign key references : CRM_OPTY_USERS Table' AS ' ';
ALTER TABLE CRM_OPTY_USERS ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID); 

-- Create foreign key references : CRM_ACCT_USERS
SELECT 'Create foreign key references : CRM_ACCT_USERS Table' AS ' ';
ALTER TABLE CRM_ACCT_USERS ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID); 

-- Create foreign key references : CRM_ACCT_OPTY
SELECT 'Create foreign key references : CRM_ACCT_OPTY Table' AS ' ';
ALTER TABLE CRM_ACCT_OPTY ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID); 

-- Create foreign key references : CRM_ROLES
SELECT 'Create foreign key references : CRM_ROLES Table' AS ' ';
ALTER TABLE CRM_ROLES ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID);

-- Create foreign key references : CRM_PRIVILEGES
SELECT 'Create foreign key references : CRM_ROLES Table' AS ' ';
ALTER TABLE CRM_PRIVILEGES ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID); 

-- Create foreign key references : CRM_USER_ROLES
SELECT 'Create foreign key references : CRM_ROLES Table' AS ' ';
ALTER TABLE CRM_USER_ROLES ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID); 

-- Create foreign key references : CRM_ROLE_PRIVILEGES
SELECT 'Create foreign key references : CRM_ROLES Table' AS ' ';
ALTER TABLE CRM_ROLE_PRIVILEGES ADD FOREIGN KEY (TENANT_ID) REFERENCES CRM_COMPANY(ROW_ID);

-- After creating all the tables we need to insert the default company and user.


-- Create Default company
SELECT 'Create Super company' AS ' ';
INSERT INTO CRM_COMPANY(NAME, ADDRESS, PRIMARY_CONTACT,ACTIVE_FLG,DELETED_STATE, 
CREATED,CREATED_BY, UPDATED, UPDATED_BY) VALUES("SUPER", "Bangalore", "superadmin", 'Y','N', curdate(),-1,curdate(),-1); 


-- Create Default User
SELECT 'Create Superadmin  user' AS ' ';
INSERT INTO CRM_USERS(NAME ,
 USERNAME ,
 PASSWORD ,
 CREATED ,
 CREATED_BY ,
 UPDATED ,
 UPDATED_BY ,
 TENANT_ID, 
 ACTIVE_FLG,
 DELETED_STATE ) VALUES("Super Admin", "superadmin", "P@ssword1", curdate(), -1, curdate(), -1, 1,'Y','N'); 

-- Create Roles
SELECT 'Create Company Administrator role' AS '';
INSERT INTO CRM_ROLES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("ADMINISTRATOR", "This user is the administrator for the company", 1);

SELECT 'Create Company User role' AS '';
INSERT INTO CRM_ROLES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("SUPPORTUSER", "This user is a support user of the company", 1);

-- Create Privileges

SELECT 'Create  READ ALL' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("READ_ALL", "This is a privilege to add all types of records into the database", 1);

SELECT 'Create ADD ALL' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("ADD_ALL", "This is a privilege to add all types of records into the database", 1);

SELECT 'Create DELETE ALL' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("DELETE_ALL", "This is a privilege to Delete all types of records into the database", 1);

SELECT 'Create EDIT ALL' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("EDIT_ALL", "This is a privilege to add all types of records into the database", 1);

SELECT 'Create READ COMPANY' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("READ_COMPANY", "This is a privilege to add company into the database", 1);

SELECT 'Create ADD COMPANY' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("ADD_COMPANY", "This is a privilege to add company into the database", 1);

SELECT 'Create DELETE COMPANY' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("DELETE_COMPANY", "This is a privilege to DELETE COMPANY", 1);

SELECT 'Create EDIT COMPANY' AS '';
INSERT INTO CRM_PRIVILEGES(NAME, DESCRIPTION, TENANT_ID ) VALUES ("EDIT_COMPANY", "This is a privilege to EDIT COMPANY", 1);

-- Create Role Privileges
SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 1, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 2, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 3, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 4, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 5, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 6, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 7, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (1, 8, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 1, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 2, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 3, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 4, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 5, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 6, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 7, 1);

SELECT 'Create ADMINISTRTOR ROLE PRIVILEGES' AS '';
INSERT INTO CRM_ROLE_PRIVILEGES(ROLE_ID, PRIVILEGE_ID, TENANT_ID ) VALUES (2, 8, 1);


-- Create account types

SELECT 'Create ACCOUNT TYPES ' AS '';
INSERT INTO CRM_ACCOUNT_TYPE( NAME, DESCRIPTION) VALUES ("ASSET", "THIS IS INCOME ACCOUNT");

SELECT 'Create ACCOUNT TYPES ' AS '';
INSERT INTO CRM_ACCOUNT_TYPE( NAME, DESCRIPTION) VALUES ("LIABILITY", "THIS IS LIABILITY ACCOUNT");

SELECT 'Create ACCOUNT TYPES ' AS '';
INSERT INTO CRM_ACCOUNT_TYPE( NAME, DESCRIPTION) VALUES ("EQUITY", "THIS IS EQUITY OR CAPITAL  ACCOUNT");

SELECT 'Create ACCOUNT TYPES ' AS '';
INSERT INTO CRM_ACCOUNT_TYPE( NAME, DESCRIPTION) VALUES ("INCOME", "THIS IS INCOME ACCOUNT");


SELECT 'Create ACCOUNT TYPES ' AS '';
INSERT INTO CRM_ACCOUNT_TYPE( NAME, DESCRIPTION) VALUES ("EXPENSE", "THIS IS EXPENSE ACCOUNT");


































