SELECT 'Dropping database DAIRYONDEMAND' AS ' ';
DROP DATABASE IF EXISTS DAIRYONDEMAND;


DROP USER  'TestCRMCore'@'localhost';
CREATE USER 'TestCRMCore'@'localhost' IDENTIFIED BY 'TestCRMCore';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE   ON DAIRYONDEMAND.*   TO 'TestCRMCore'@'localhost';

SELECT 'Creating database DAIRYONDEMAND' AS ' ';
CREATE DATABASE DAIRYONDEMAND;

USE DAIRYONDEMAND;

SELECT 'dropping the tables' AS ' ';
DROP TABLE IF EXISTS DOD_COMPANY;  SELECT 'Apartment complex/society ';
 DROP TABLE IF EXISTS DOD_ORD_PREF; SELECT 'Product preference table, which will let the vendor know what the product preferences of the user are.'; 
 DROP TABLE IF EXISTS DOD_ORDER; SELECT 'Product ondemand preference'; 
 DROP TABLE IF EXISTS DOD_ORDER_DETAILS; 
 DROP TABLE IF EXISTS DOD_PRD_MASTER; SELECT 'Product master table, where the most recent price of the product is mentioned.';
 DROP TABLE IF EXISTS DOD_CUST_PROFILE; SELECT  'Store the user profile here.';
 DROP TABLE IF EXISTS DOD_VEND_PROFILE; SELECT 'Store the vendor profile here.'; 
 DROP TABLE IF EXISTS DOD_EMPLOYEES; SELECT 'Data entry operator'; 
 
 SELECT 'tables dropped' AS ' ';

 SELECT 'creating table DOD_USERS' AS ' ';    
CREATE TABLE DOD_USERS( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
 NAME VARCHAR(30) ,
 USERNAME VARCHAR(30) ,
 PASSWORD VARCHAR(100) ,
 EMAIL VARCHAR(255),
 FIRSTNAME VARCHAR(50), 
 LASTNAME VARCHAR(50), 
 FULLNAME VARCHAR(50), 
 SALUTATION VARCHAR(10), 
 TITLE VARCHAR(255), 
 PHONE_HOME VARCHAR(50), 
 PHONE_MOBILE VARCHAR(50), 
 PHONE_OFFICE VARCHAR(50), 
 PRIMARY_ADDRESS_STREET VARCHAR(150), 
 PRIMARY_ADDRESS_CITY VARCHAR(100), 
 PRIMARY_ADDRESS_STATE VARCHAR(100), 
 PRIMARY_ADDRESS_POSTALCODE VARCHAR(20), 
 PRIMARY_ADDRESS_COUNTRY VARCHAR(255), 
 BIRTHDATE DATETIME, 
 PICTURE VARCHAR(255),
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 CREATED_BY MEDIUMINT,
 UPDATED TIMESTAMP ,
 UPDATED_BY MEDIUMINT,
 ACTIVE_FLG CHAR(1),
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT, 
PARENT_ID MEDIUMINT );
 
 SELECT 'creating table DOD_COMPANY' AS ' ';
CREATE TABLE DOD_COMPANY( ROW_ID MEDIUMINT AUTO_INCREMENT     PRIMARY KEY ,
 NAME VARCHAR(255) ,
 ADDRESS VARCHAR(512) ,
 PRIMARY_CONTACT VARCHAR(255), 
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
  CREATED_BY MEDIUMINT,
  UPDATED TIMESTAMP ,
  UPDATED_BY MEDIUMINT,
  ACTIVE_FLG CHAR(1),
 DELETED_STATE CHAR(1));
 
SELECT 'creating table DOD_PRD_PREF' AS ' ';
CREATE TABLE DOD_ORD_PREF( ROW_ID MEDIUMINT AUTO_INCREMENT     PRIMARY KEY ,
 CUST_ID MEDIUMINT, 
 PRD_ID MEDIUMINT, 
 PRD_QTY MEDIUMINT,
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 TENANT_ID MEDIUMINT, 
 DELETED_STATE CHAR(1)
 );
  
 'This is a daily transaction table to calculate the demand for the product on a daily basis.'
 'We can copy the rows from DOD_PRD_PREF table by running a daily job and consider that as daily ondemand preference' 
SELECT 'creating table DOD_ORDER' AS ' ';    
CREATE TABLE DOD_ORDER( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
 ORD_DATE TIMESTAMP, 
 CUST_ID MEDIUMINT, 
 REQ_DATE TIMESTAMP, 
 SHIPPED_DATE TIMESTAMP, 
 SHIP_ADDRESS VARCHAR(100), 
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 TENANT_ID MEDIUMINT,
 DELETED_STATE CHAR(1));
 
SELECT 'creating table DOD_ORD_DETAILS' AS ' ';    
CREATE TABLE DOD_ORDER_DETAILS( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
 ORDER_ID MEDIUMINT, 
 PRD_ID MEDIUMINT, 
 UNIT_PRICE DECIMAL(5,2), 
 PRD_QTY MEDIUMINT, 
 CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT 
);
 
 
 
SELECT 'creating table DOD_PRD_PRCMASTER' AS ' ';    
CREATE TABLE DOD_PRD_MASTER( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
PRD_NAME VARCHAR(70),
VENDOR_ID MEDIUMINT, 
QTY_PER_UNIT VARCHAR(30), 
PRD-IMAGE-PATH VARCHAR(256),
UNIT_PRICE DECIMAL(5,3),
UNITS_IN_STOCK SMALLINT, 
CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT 
);

SELECT 'creating table DOD_CUST_PROFILE' AS ' ';    
CREATE TABLE DOD_CUST_PROFILE( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
NAME  VARCHAR(70),
ADDRESS VARCHAR(70), 
PHONE VARCHAR(30), 
USERNAME VARCHAR(30) ,
PASSWORD VARCHAR(100) ,
CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT 

);

SELECT 'creating table DOD_VEND_PROFILE' AS ' ';    
CREATE TABLE DOD_VEND_PROFILE( ROW_ID MEDIUMINT AUTO_INCREMENT    PRIMARY KEY ,
NAME  VARCHAR(70),
ADDRESS VARCHAR(70), 
PHONE VARCHAR(30), 
 USERNAME VARCHAR(30) ,
 PASSWORD VARCHAR(100) ,
CREATED TIMESTAMP NOT NULL DEFAULT NOW() ,
 DELETED_STATE CHAR(1),
 TENANT_ID MEDIUMINT

);



-- Create foreign key references : DOD_ORD_PREF Table
SELECT 'Create foreign key references : DOD_ORD_PREF Table' AS ' '; 
ALTER TABLE DOD_ORD_PREF ADD FOREIGN KEY( TENANT_ID)   REFERENCES DOD_COMPANY(ROW_ID); 
ALTER TABLE DOD_ORD_PREF ADD FOREIGN KEY( CUST_ID)   REFERENCES DOD_CUST_PROFILE(ROW_ID); 
ALTER TABLE DOD_ORD_PREF ADD FOREIGN KEY( PRD_ID)   REFERENCES DOD_PRD_MASTER(ROW_ID); 


-- Create foreign key references : DOD_ORDER Table
SELECT 'Create foreign key references : DOD_ORDER' AS ' ';
ALTER TABLE DOD_ORDER ADD FOREIGN KEY (TENANT_ID) REFERENCES DOD_COMPANY(ROW_ID); 
ALTER TABLE DOD_ORDER ADD FOREIGN KEY( CUST_ID)   REFERENCES DOD_CUST_PROFILE(ROW_ID); 



-- Create foreign key references : DOD_ORDER_DETAILS Table
SELECT 'Create foreign key references : DOD_ORDER_DETAILS Table' AS ' ';
ALTER TABLE DOD_ORDER_DETAILS ADD FOREIGN KEY (TENANT_ID) REFERENCES DOD_COMPANY(ROW_ID); 
ALTER TABLE DOD_ORDER_DETAILS ADD FOREIGN KEY( ORDER_ID)   REFERENCES DOD_ORDER(ROW_ID); 
ALTER TABLE DOD_ORD_PREF ADD FOREIGN KEY( PRD_ID)   REFERENCES DOD_PRD_MASTER(ROW_ID); 


-- Create foreign key references : DOD_PRD_MASTER
SELECT 'Create foreign key references : DOD_PRD_MASTER ' AS ' ';
ALTER TABLE DOD_PRD_MASTER ADD FOREIGN KEY (TENANT_ID) REFERENCES DOD_COMPANY(ROW_ID); 
ALTER TABLE DOD_PRD_MASTER ADD FOREIGN KEY( VENDOR_ID)   REFERENCES DOD_VEND_PROFILE(ROW_ID); 

-- Create foreign key references : DOD_CUST_PROFILE
SELECT 'Create foreign key references : DOD_CUST_PROFILE Table' AS ' ';
ALTER TABLE DOD_CUST_PROFILE ADD FOREIGN KEY (TENANT_ID) REFERENCES DOD_COMPANY(ROW_ID); 

-- Create foreign key references : DOD_VEND_PROFILE
SELECT 'Create foreign key references : DOD_VEND_PROFILE Table' AS ' ';
ALTER TABLE DOD_VEND_PROFILE ADD FOREIGN KEY (TENANT_ID) REFERENCES DOD_COMPANY(ROW_ID);


-- After creating all the tables we need to insert the default company and user.



-- Create Default company
SELECT 'Create Super company' AS ' ';
INSERT INTO DOD_COMPANY(NAME, ADDRESS, PRIMARY_CONTACT,ACTIVE_FLG,DELETED_STATE, 
CREATED,CREATED_BY, UPDATED, UPDATED_BY) VALUES("SUPER", "Bangalore", "superadmin", 'Y','N', curdate(),-1,curdate(),-1); 

SELECT 'Create Dairyondemand company' AS ' ';
INSERT INTO DOD_COMPANY(NAME, ADDRESS, PRIMARY_CONTACT,ACTIVE_FLG,DELETED_STATE, 
CREATED,CREATED_BY, UPDATED, UPDATED_BY) VALUES("Dairy Ondemand", "Bangalore", "dod", 'Y','N', curdate(),-1,curdate(),-1); 


-- Create Default User
SELECT 'Create Superadmin  user' AS ' ';
INSERT INTO DOD_USERS(NAME ,
 USERNAME ,
 PASSWORD ,
 CREATED ,
 CREATED_BY ,
 UPDATED ,
 UPDATED_BY ,
 TENANT_ID, 
 ACTIVE_FLG,
 DELETED_STATE ) VALUES("Super Admin", "superadmin", "P@ssword1", curdate(), -1, curdate(), -1, 1,'Y','N'); 

-- Create Default User
SELECT 'Create Superadmin  user' AS ' ';
INSERT INTO DOD_USERS(NAME ,
 USERNAME ,
 PASSWORD ,
 CREATED ,
 CREATED_BY ,
 UPDATED ,
 UPDATED_BY ,
 TENANT_ID, 
 ACTIVE_FLG,
 DELETED_STATE ) VALUES("Dairy Ondemand", "dod", "P@ssword1", curdate(), -1, curdate(), -1, 2,'Y','N'); 

















